In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r'C:\Users\laksh\Downloads\Subscription Breakdown\dropbox_subscription_plans.csv')

In [4]:
df.shape

(16, 7)

In [5]:
df.dtypes

plan_id                   int64
plan_name                   str
segment                     str
fixed_costs               int64
variable_cost_per_user    int64
revenue_per_subscriber    int64
current_subscribers       int64
dtype: object

In [6]:
df.isna().sum()

plan_id                   0
plan_name                 0
segment                   0
fixed_costs               0
variable_cost_per_user    0
revenue_per_subscriber    0
current_subscribers       0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
df.head()

,plan_id,plan_name,segment,fixed_costs,variable_cost_per_user,revenue_per_subscriber,current_subscribers
0,301,Basic,Consumer,12500,3,10,4000
1,302,Plus,Consumer,40000,6,25,3000
2,303,Premium,Consumer,90000,12,50,1500
3,304,Family,Consumer,45000,9,30,2000
4,305,Starter,Consumer,22000,5,14,3500

In [14]:
## Total Count of Subscribers per plan
df.groupby('plan_name')['current_subscribers'].sum().sort_values(ascending=False)

plan_name
Business      6000
Education     5000
Team          5000
Basic         4000
Pro           4000
Enterprise    3500
Starter       3500
Plus          3000
Elite         2800
Student       2500
Family        2000
Legacy        2000
Premium       1500
Promo         1500
Nonprofit     1200
On-Prem        500
Name: current_subscribers, dtype: int64

In [22]:
df['total_revenue'] = df['revenue_per_subscriber'] * df['current_subscribers']
df['total_variable_costs'] = df['variable_cost_per_user'] * df['current_subscribers']
df['total_costs'] = df['fixed_costs'] + df['total_variable_costs']
df['profit'] = df['total_revenue'] - df['total_costs']

In [25]:
df.head(16)

,plan_id,plan_name,segment,fixed_costs,variable_cost_per_user,revenue_per_subscriber,current_subscribers,total_revenue,total_variable_cost,total_costs,profit,total_variable_costs
0,301,Basic,Consumer,12500,3,10,4000,40000,12000,24500,15500,12000
1,302,Plus,Consumer,40000,6,25,3000,75000,18000,58000,17000,18000
2,303,Premium,Consumer,90000,12,50,1500,75000,18000,108000,-33000,18000
3,304,Family,Consumer,45000,9,30,2000,60000,18000,63000,-3000,18000
4,305,Starter,Consumer,22000,5,14,3500,49000,17500,39500,9500,17500
5,306,Elite,Consumer,130000,20,75,2800,210000,56000,186000,24000,56000
6,307,Team,Business,120000,18,60,5000,300000,90000,210000,90000,90000
7,308,Business,Business,250000,35,120,6000,720000,210000,460000,260000,210000
8,309,Pro,Business,180000,28,90,4000,360000,112000,292000,68000,112000
9,310,Enterprise,Business,600000,90,300,3500,1050000,315000,915000,135000,315000
10,311,Education,Education,15000,2,6,5000,30000,10000,25000,5000,10000
11,312,Student,Education,6000,1,5,2500,12500,2500,8500,4000,2500
12,313,Nonprofit,Education,9000,3,8,1200,9600,3600,12600,-3000,3600
13,314,Promo,Consumer,12000,8,8,1500,12000,12000,24000,-12000,12000
14,315,Legacy,Legacy,9000,9,5,2000,10000,18000,27000,-17000,18000
15,316,On-Prem,Business,500000,218,220,500,110000,109000,609000,-499000,109000

In [26]:
#How each plan's profit changes as its subscriber count grows
df.groupby(['plan_name','current_subscribers'])['profit'].sum().sort_values(ascending=False)

plan_name   current_subscribers
Business    6000                   260000
Enterprise  3500                   135000
Team        5000                    90000
Pro         4000                    68000
Elite       2800                    24000
Plus        3000                    17000
Basic       4000                    15500
Starter     3500                     9500
Education   5000                     5000
Student     2500                     4000
Family      2000                    -3000
Nonprofit   1200                    -3000
Promo       1500                   -12000
Legacy      2000                   -17000
Premium     1500                   -33000
On-Prem     500                   -499000
Name: profit, dtype: int64